from django.urls import path
from . import views

urlpatterns = [
    path('', views.BookListView.as_view()),
    path('recent', views.RecentBooksView.as_view()),
    path('popular', views.PopularBooksView.as_view()),
    path('top-rated', views.TopRatedBooksView.as_view()),
    path('metadata-search', views.BookMetadataSearchView.as_view()),
    path('upload', views.BookUploadView.as_view()),
    path('create-audio', views.AudioBookCreateView.as_view()),
    path('<str:book_id>/files', views.BookFilesView.as_view()),
    path('<str:book_id>/files/<str:file_id>', views.BookFileDetailView.as_view()),
    path('<str:book_id>/convert', views.BookConvertView.as_view()),
    path('<str:book_id>/download/<str:fmt>', views.BookDownloadView.as_view()),
    path('<str:book_id>/read', views.BookReadView.as_view()),
    path('<str:book_id>/cover', views.BookCoverView.as_view()),
    path('<str:book_id>/progress', views.BookProgressView.as_view()),
    path('<str:book_id>/rate', views.BookRateView.as_view()),
    path('<str:book_id>/ratings', views.BookRatingsView.as_view()),
    path('<str:book_id>/ratings/<str:rating_id>', views.BookRatingDetailView.as_view()),
    path('<str:book_id>/annotations', views.AnnotationListView.as_view()),
    path('<str:book_id>/annotations/<str:annotation_id>', views.AnnotationDetailView.as_view()),
    path('<str:book_id>/comments', views.BookCommentListView.as_view()),
    path('<str:book_id>/comments/<str:comment_id>', views.BookCommentDetailView.as_view()),
    path('<str:book_id>/visibility', views.BookVisibilityView.as_view()),
    path('<str:book_id>/analyze', views.BookAnalyzeView.as_view()),
    path('<str:book_id>/analyze/stream', views.BookAnalyzeStreamView.as_view()),
    path('<str:book_id>/toc', views.BookTOCView.as_view()),
    path('<str:book_id>/audio', views.AudioChapterListView.as_view()),
    path('<str:book_id>/audio/progress', views.AudioProgressView.as_view()),
    path('<str:book_id>/audio/<str:chapter_id>/stream', views.AudioChapterStreamView.as_view()),
    path('<str:book_id>/audio/<str:chapter_id>', views.AudioChapterDetailView.as_view()),
    path('<str:book_id>', views.BookDetailView.as_view()),
]
