# Generated by Django 5.1.4 on 2026-06-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_annotation_id_alter_bookauthor_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_public', '-created_at'], name='book_public_created_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-avg_rating'], name='book_avg_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-download_count'], name='book_download_count_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language'], name='book_language_idx'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['user', '-last_read'], name='progress_user_last_read_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['book', 'user'], name='annotation_book_user_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['book', 'is_public'], name='annotation_book_public_idx'),
        ),
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['book', '-created_at'], name='rating_book_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcomment',
            index=models.Index(fields=['book', 'created_at'], name='comment_book_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcomment',
            index=models.Index(fields=['parent'], name='comment_parent_idx'),
        ),
    ]
